name: Update YouTube M3U

on:
  schedule:
    - cron: '0 */2 * * *'  # 2 saatte bir
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository'yi indir
      uses: actions/checkout@v4
      
    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: yt-dlp kütüphanesini yükle
      run: |
        pip install yt-dlp
        
    - name: YouTube M3U scriptini çalıştır (YT-DLP)
      run: python youtube_m3u_generator.py
      
    - name: Değişiklikleri kaydet ve gönder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add youtube.m3u
        git diff --staged --quiet || git commit -m "YouTube M3U güncellendi (YT-DLP) - $(date +'%Y-%m-%d %H:%M')"
        git push
